### ISSUE TITLE
"Raw Data" Tab: Hostname Column

### ISSUE THREAD

**Issue by sagansapien** [CyberSecDef/scans2reports#24]
filter has two entries for a given hostname if CKL and ACAS is ingested.
Scan type CKL: Hostname = **HOSTNAME**
Scan type ACAS: Hostname = **hostname.fqdn.mil**
Recommend to grab FQDN instead of hostname from CKL file, so hostname filter returns 1 host with both scan types. Also force to lower case?

**Comment by CyberSecDef** [comment]
For CKLS
if FQDN, use it
if not FQDN, but hostname...use hostname
if not fqdn and not hostname, use IP
if not fqdn, not hostname, not ip, use empty string
