### ISSUE TITLE
Asset Traceability tab: "ACAS Port Range 0-65535" always false

### ISSUE THREAD

**Issue by sagansapien** [CyberSecDef/scans2reports#37]

**Comment by CyberSecDef** [comment]
Please confirm Port 19506 has a section called "Port Range" that lists something.  This should be true if that value is "0-65535" or "all ports".  if its not one of those, it shows as false.  If there are other 'options' that would default to true, let me know what they should be.

**Comment by sagansapien** [comment]
<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="19506" pluginName="Nessus Scan Information" pluginFamily="Settings">
<plugin_output>Information about this scan : 

Nessus version : 8.6.0
Plugin feed version : 202002271740
Scanner edition used : Nessus
Scan type : Normal
Scan policy used : **REDACTED**
Scanner IP : **REDACTED**
Port scanner(s) : wmi_netstat 
Port range : 0-65535
Thorough tests : no
Experimental tests : no
Paranoia level : 1
Report verbosity : 1
Safe checks : yes
Optimize the test : yes
Credentialed checks : yes, as **REDACTED**; via SMB
Patch management checks : None
CGI scanning : disabled
Web application tests : disabled
Max hosts : 30
Max checks : 5
Recv timeout : 5
Backports : None
Allow post-scan editing: Yes
Scan Start Date : 2020/2/28 18:27 UTC
Scan duration : 582 sec
ScanPolicy:**REDACTED**
Credentialed_Scan:true
LastAuthenticatedResults:1582915060</plugin_output>
