### ISSUE TITLE
Merge duplicate fields from Asset Traceability and Automated Scan Info

### ISSUE THREAD

**Issue by sagansapien** [CyberSecDef/scans2reports#53]
Most of the fields from the automated scans info tab already live in the Traceability tab. fix logic for scan date/duration/feed date in the traceability tab. Then get rid of the automated scan info tab

**Comment by CyberSecDef** [comment]
These two reports have been updated to properly show information.
The Asset Traceability tab is intended to show traceability from the host -> scan perspective.
The Scan Summary tab is intended tho show traceability from the scan -> host perspective.
Keeping both tabs for informational purpose.
