### ISSUE TITLE
Asset Traceability tab: remove "STIG CKL Credentialed Checks" column

### ISSUE THREAD

**Issue by sagansapien** [CyberSecDef/scans2reports#55]
it's always true so this datapoint is NA.

**Comment by sagansapien** [comment]
Ditto for "SCAP Credentialed Checks"

**Comment by CyberSecDef** [comment]
SCAP will come back with non-credentialed scans (I've seen it) when bad scans are run.
Keeping CKL for consistency purpose as the column can be deleted if not needed.
