### ISSUE TITLE
Automated Scan Info Tab: Scan to Feed Difference Wrong

### ISSUE THREAD

**Issue by sagansapien** [CyberSecDef/scans2reports#58]
Per plugin 19506

Plugin feed version : 202002072110
Scan Start Date : 2020/2/10 13:18 UTC
Scan duration : 434 sec

Automated Scan Info Tab:

202002072110
2020/2/10   13:18 UTC
434 sec

Scan to Feed Difference: **19**

Should be 3.

**Comment by sagansapien** [comment]
The same host on the Asset Traceability tab has the following:

ACAS Scanner Version: 8.6.0
ACAS Feed Version: 202002260830
ACAS Start Date: Thu Feb   27 13:08:52 2020
ACAS Days between...: 1

This feed version matches results from OTHER hosts in the nessus file. We're getting hosts crossed up as well.

**Comment by CyberSecDef** [comment]
"We're getting hosts crossed up as well."

Can you explain that in more detail?

**Comment by sagansapien** [comment]
The results from each tab for the same hostname appear to relate to different hosts. Everything but the scan to feed difference (19) is accurate on the Automated Scan Info tab after reviewing the source data for that host. All of the data for the same host on the traceability tab is incorrect and appears to relate to a different host altogether.

**Comment by CyberSecDef** [comment]
just the traceability tab
and the date difference is incorrect on both
the automated scan info tab is more-right

**Comment by CyberSecDef** [comment]
This appears to have been resovled via the engine re-write
