### ISSUE TITLE
Asset Traceability tab: ACAS Scan Policy column is blank

### ISSUE THREAD

**Issue by sagansapien** [CyberSecDef/scans2reports#72]
This column was blank after parsing a .nessus file.

**Comment by CyberSecDef** [comment]
Can you confirm that nessus file has a 'policy' field?

/NessusClientData_v2/Policy/policyName

**Comment by sagansapien** [comment]
<PolicyName>Merged .Nessus Scans</PolicyName>

**Comment by CyberSecDef** [comment]
Roger that.  Will have to update the merge methods to include the first policy found.

**Comment by sagansapien** [comment]
On the Automated Scan Info tab, the correct policy is listed: 

9e489273-7226-532a-8b2b-c5171ef7cffb-180542553/Full   Safe Scan - All Ports - Thorough Check

Just remove the scan policy column from the Asset Traceability tab since it's blank, and is available elsewhere. Thus removing the duplication of data

**Comment by CyberSecDef** [comment]
I would rather have the asset traceability tab and the automated scan info tabs both stand on their own.  I'll dig into why its showing on one tab but not the other and come up with a solution

**Comment by CyberSecDef** [comment]
This should be fixed with the change to the asset traceability tab.

ALSO....regenerate all the MERGE and SPLIT nessus files to rule out those.  There may have been a bug in the original split and merge methods.
