### ISSUE TITLE
GUI: Blue Box Text

### ISSUE THREAD

**Issue by CyberSecDef** [CyberSecDef/scans2reports#92]
Add a bullet list of what can be imported with details:
- SCAP
- CKL
- ACAS
- POAM - for mitigation statements
- Test Results - For control mapping

**Comment by CyberSecDef** [comment]
XML (SCAP)
.XLSX (Old POAM with existing Mitigation Statements)
.XLSX (Test Report export from eMASS, needed for control mapping)
etc

**Comment by sagansapien** [comment]
.XML (SCAP / XCCDF)

**Comment by sagansapien** [comment]
.XLSX (Existing POAM with Mitigation Statements)

**Comment by sagansapien** [comment]
.NESSUS (ACAS)
